# Generated by Django 5.0.2 on 2024-04-11 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="invited_people",
            field=models.ManyToManyField(
                related_name="teams_invited_to", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(
                default="a25efb3b8afbe148b422999758b45819", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(
                default="947dcb5c870be1b5da40aa1d230a6c3b", max_length=32, unique=True
            ),
        ),
    ]
