# Generated by Django 5.0.2 on 2024-04-12 11:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_invited_people_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(
                default="cd88b08753bf99b890ac466e03f25bc7", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(
                default="f26782195599bbbed0dc9f8fe95fea00", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=200, populate_from="title", unique=True
            ),
        ),
    ]
