# Generated by Django 5.0.2 on 2024-04-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_invitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="uuid",
            new_name="id",
        ),
    ]
