# Generated by Django 5.0.2 on 2024-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="color",
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(
                default="b3e7998393dc79818754a423d7928cf0", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(
                default="2582d9ae47f184d0cf2eee994800224c", max_length=32, unique=True
            ),
        ),
    ]
