# Generated by Django 5.0.2 on 2024-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_remove_team_color_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(
                default="63cf4d88f4b32a2b3512b59a20d1012d", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(
                default="4e01e5406eff2de4d5e9c2233bb70022", max_length=32, unique=True
            ),
        ),
    ]
