# Generated by Django 5.0.2 on 2024-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(
                default="4f9d323cd20e96c4d3f35132c62f008f", max_length=32, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(
                default="8833dc9411a1bde490db186e5d8fb13f", max_length=32, unique=True
            ),
        ),
    ]
