# Generated by Django 5.0.2 on 2024-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="join_key_common",
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="join_key_selective",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
