# Generated by Django 5.0.2 on 2024-05-28 13:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_alter_team_join_key_common_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                max_length=200,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
