# Generated by Django 5.0.2 on 2024-05-28 13:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_alter_team_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=200, populate_from="title", unique=True
            ),
        ),
    ]
