# Generated by Django 5.0.6 on 2025-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_member_status_task_taskstep_tasktag_task_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
