# Generated by Django 4.2 on 2025-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_task_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
