# Generated by Django 5.0.1 on 2024-02-01 14:15

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="links",
            field=models.ManyToManyField(null=True, to="users.link"),
        ),
    ]
