# Generated by Django 5.0.1 on 2024-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="links",
            field=models.ManyToManyField(related_name="users", to="users.link"),
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
