# Generated by Django 5.0.2 on 2024-05-28 12:50

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(null=True, use_pytz=True),
        ),
    ]
