# Generated by Django 5.0.1 on 2024-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_link_user_description_user_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="links",
            field=models.ManyToManyField(to="users.link"),
        ),
    ]
