# Generated by Django 5.0.6 on 2024-09-24 09:29

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True, null=True, use_pytz=True
            ),
        ),
    ]
